
title: LOTTunnels

exclude: ['/Gemfile', '/Makefile', '/README.md', '/NOTICE.md', 'LICENSE', '/YML-TEMPLATE.yml', '/scripts']

permalink: pretty

collections:
  lottunnels:
    output: true

defaults:
  - scope:
      path: '_lottunnels'
    values:
      layout: 'bin'
